# Generated by Django 6.0.1 on 2026-01-17 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage_amount', models.PositiveIntegerField(help_text='Amount of dosage (e.g., 500)')),
                ('dosage_unit', models.CharField(help_text='Unit of dosage (e.g., mg, ml, pill)', max_length=50)),
                ('frequency_amount', models.PositiveIntegerField(help_text='Frequency amount (e.g., every 6)')),
                ('frequency_unit', models.CharField(help_text='Frequency unit (e.g., hours, days)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
